name: mark_my_words
description: A static blog generator.
# version: 1.0.0
# homepage: https://github.com/johanalkstal/mark-my-words
# author: Johan Alkstål <hi@johanalkstal.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  logger: ^0.7.0+2
  markdown: ^2.0.3
  mustache: ^1.1.1
  shelf: ^0.7.5
  shelf_static: ^0.2.8
  yaml: ^2.1.16

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
